library(MASS)
library(caret)
library(refund)
library(foreach)
library(data.table)
library(stringr)
args = commandArgs(trailingOnly=TRUE)
code = args[1]
source("FunFor/R/FunFor.R")
Y_train = as.data.frame(fread(file=str_glue("temp/temp_{code}_ytrain.csv"), header=FALSE))
Y_test = as.data.frame(fread(file=str_glue("temp/temp_{code}_ytest.csv"), header=FALSE))
n_col = ncol(Y_train)
colnames(Y_train) = as.character(1:n_col)
colnames(Y_test) = as.character(1:n_col)
X_train = as.data.frame(fread(file=str_glue("temp/temp_{code}_Xtrain.csv"), header=FALSE))
X_test = as.data.frame(fread(file=str_glue("temp/temp_{code}_Xtest.csv"), header=FALSE))
print("Files loaded")
formula = paste(str_glue("data[, 1:{n_col}]"), "~", paste(names(X_train), collapse = "+"))
data = cbind(Y_train, X_train)
newX = cbind(Y_test, X_test)
funfor_fit = FunFor(formula, data, mtry = 1000, ntree = 3, npc = 3, m_split = 15, smooth=FALSE)
y_pred = predict(funfor_fit, X_test)
write.csv(y_pred, str_glue("temp/temp_{code}_ypred.csv"))