library(MASS)
library(caret)
library(refund)
library(foreach)
library(data.table)
source("R/FunFor.R")
Y_train = as.data.frame(fread(file="y_train.csv"))
Y_test = as.data.frame(fread(file="y_test.csv"))
colnames(Y_train) = as.character(1:7)
colnames(Y_test) = as.character(1:7)
X_train = as.data.frame(fread(file="X_train.csv"))
X_test = as.data.frame(fread(file="X_test.csv"))
print("Files loaded")
formula = paste("data[, 1:7]", "~", paste(names(X_train), collapse = "+"))
data = cbind(Y_train, X_train)
newX = cbind(Y_test, X_test)
funfor_fit = FunFor(formula, data, mtry = 1000, ntree = 15, npc = 3, m_split = 15, smooth=FALSE)
y_pred = predict(funfor_fit, X_test)
write.csv(y_pred, "y_pred.csv")